### ISSUE TITLE
[dev.icinga.com #13257] Remove cluster/client mode "bottom up" w/ repository.d and node update-config

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4799]
# Tasks

- [x] Announcement: https://www.icinga.com/2016/12/13/icinga-2-v2-6-and-icinga-web-2-v2-4-released/ and follow-ups https://www.icinga.com/2017/08/02/icinga-2-v2-7-0-released/ 
- [x] CLI command: node {list,add,remove,blacklist,whitelist,update-config}
- [x] CLI command: repository (experimental already)
- [x] Cluster messages: UpdateRepository
- [x] Specific timers and file IO handling
- [x] Debug logging for unknown cluster messages (already exists)
- [x] Drop /var/lib/icinga2/api/repository/ from CMakeLists.txt and packages
- [x] Drop /var//lib/icinga2/repository/changes from CMakeLists.txt and packages
- [x] Configuration: Drop "repository.d" inclusion in icinga2.conf
- [x] Docs: "Bottom Up" and "Migration to Top Down" will be removed
- [x] Docs: CLI commands update
- [x] Docs: Troubleshooting explains duplicated check results - the note on bottom up should be removed. This chapter should stay, since local conf.d inclusion is still the default before 2.8.
- [x] Docs: Upgrade Note for 2.8
- [x] Code cleanup: `repository` references

# Original content

This issue has been migrated from Redmine: https://dev.icinga.com/issues/13257

**Created by mfriedrich on 2016-11-18 17:10:02 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2017-01-14 13:09:08 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

Following [\#13255.](https://dev.icinga.com/issues/13255)

Collects all remaining issues as child issues.

---

**Subtasks**:

* [Bug 7632 - Please allow one to disable "repository"](https://dev.icinga.com/issues/7632)
* [Feature 8213 - HA-Setup with update-config](https://dev.icinga.com/issues/8213)
* [Bug 9964 - icinga2 node update should not write config for blacklisted zones/host](https://dev.icinga.com/issues/9964)
* [Bug 10980 - icinga2 node update-config does not work well with indirect connected zones](https://dev.icinga.com/issues/10980)
* [Bug 11121 - Old service not deleted with 'node update-config'](https://dev.icinga.com/issues/11121)
* [Bug 12808 - Endpoint not created](https://dev.icinga.com/issues/12808)
* [Bug 13018 - Tabulation and CLI command](https://dev.icinga.com/issues/13018)
* [Bug 9267 - Behaviour of node whitelist/blacklist](https://dev.icinga.com/issues/9267)
* [Feature 9332 - Send custom attributes/groups/etc from satellite to master for node update-config](https://dev.icinga.com/issues/9332)
* [Feature 10054 - clients should send their config to master which executes checks](https://dev.icinga.com/issues/10054)
* [Bug 10411 - Documentation missing for icinga2 CLI commands.](https://dev.icinga.com/issues/10411)

**Relations**:

* relates [#13257](https://dev.icinga.com/issues/13257)
* relates [#13257](https://dev.icinga.com/issues/13257)

**Comment by dnsmichi** [comment]
Rescheduling this as 2.8 will be the last release in 2017 almost.

**Comment by dnsmichi** [comment]
I'm splitting the requirements with the disabled conf.d inclusion in setup wizards. This is not part of the removal, it doesn't hurt for now.

**Comment by dnsmichi** [comment]
Note: Existing installations stay intact. There isn't any config sync mechanism anymore, that's all about this PR.
