### ISSUE TITLE
Add ElasticWriter feature

### ISSUE THREAD

**Issue by dnsmichi** [Icinga/icinga2#5538]
## Description

Icinga 2 triggers events (check results, state changes, notifications) which should be forwarded to Elasticsearch using its HTTP API. This includes already parsed performance data metrics.

Only Elasticsearch 5.x+ is supported.

Sponsored feature.

## Tasks

- [x] Connection handling against Elasticsearch HTTP API (verify with/without auth)
- [x] Message format (JSON, specific fields)
- [x] Bulk message support 
- [x] Follow the attribute structure from icingabeat
- [x] Escape specific key/values (see LogstashWriter or icingabeat for examples)
- [x] Format timestamps in ISO format for Elasticsearch dynamic date datatype mapping
- [x] Event: CheckResult including performance data
- [x] Event: StateChange
- [x] Event: Notifications
- [x] enable_send_perfdata defaults to `false`, must be enabled
- [x] Documentation

## Hints

- Use the Vagrant box "icinga2x-elastic" and forward the Elasticsearch port
- Start with a simple event and curl against Elasticsearch
- Implement only one event and trace it in Kibana
- HTTP connection handling and message bulks are available inside the InfluxdbWriter feature
- WorkQueues and stats can be taken from InfluxDB/Graphite/etc. as example
- GelfWriter handles the messages in the same way already

## Overview

![icinga2_elastic_feature_overview_tasks](https://user-images.githubusercontent.com/382049/30034254-7331e726-91a0-11e7-939f-13f12aefa556.jpg)

**Comment by dnsmichi** [comment]
Vagrant box listen: Icinga/icinga-vagrant#94

**Comment by Crunsher** [comment]
TODO:
1. Auth&SSL
2. Documentation

**Comment by Crunsher** [comment]
Alright, did it. Auth and SSL are currently not possible because that's not part of the free package

**Comment by dnsmichi** [comment]
Thanks for your efforts 👍 

I've started a first review and added my changes as separate commits.

Things to note:

- Wording and formatting in the documentation, partially wrong identifiers
- Error handling for HTTP responses is missing
- The structure for event messages does not comply with the icingabeat format in https://github.com/Icinga/icingabeat/blob/master/beater/eventstream.go#L49
- Performance data metrics require specific prefixes, similar to how Graphite handles them
- Check results are sent for all three events, not only CheckResult
- The underscore for keys is only required for Graylog, not for Elastic
- Index sends the wrong type, this should render as `icinga2.event.<type>` similar to the icingabeat
- timestamp handling - if the checkresult was in the past, the event timestamp should reflect that (cluster replay log similar to graphite)
- Messages do not include the @timestamp field for time-based indexes in Kibana (this is the easiest index we can get) -> This is an ongoing **TODO**.

It is highly likely that we can add more attributes, but that depends on a general review from the icingebeat fields (which is just what we provide through the API event streams, see #5311).

The only real addition here is to add performance data metrics inside the `check_result` prefix.

The mentioned things above are all fixed and tested, except for the missing timestamp auto-detect datatype inside the index (details below).

## Hints

Delete all elasticsearch data:

```
curl -X DELETE 'http://localhost:9200/_all'
```

List mapping for index

```
curl -X GET 'http://localhost:9200/icinga2-2017.09.08' | python -m json.tool
```

https://www.elastic.co/blog/elasticsearch-as-a-time-series-data-store
https://gist.github.com/tegud/68c2c159275251f4063c

## TODO

### Date detection in indexes

Happens automatically if the value matches the default date detection pattern.

https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-field-mapping.html#date-detection

### Review field structure

Keep in similar to icingabeat.

**Comment by dnsmichi** [comment]
## Time-series data index pattern for date detection

timestamp must be using the following format:

```
%Y-%m-%dT%H:%M:%S.sss%z
```

where sss are the milliseonds of the current timestamp (strftime resp Utility::FormatDateTime() does not support it).

```
timestamp":"2017-09-11T10:56:21.463+0200"
```

```
curl http://localhost:9200/icinga2-2017.09.11?pretty=1

          "timestamp" : {
            "type" : "date"
          },
```

**Comment by dnsmichi** [comment]
Timestamps should be formatted similar to icingabeat.

https://github.com/Icinga/icingabeat/blob/master/beater/eventstream.go#L58

**Comment by dnsmichi** [comment]
![icinga2_elasticwriter_kibana_checkresult](https://user-images.githubusercontent.com/382049/30272157-66cd6af2-96f3-11e7-8909-dafd5b7362a4.png)

**Comment by dnsmichi** [comment]
## Kibana Index Pattern

![icinga2_elasticwriter_kibana_index_pattern](https://user-images.githubusercontent.com/382049/30272384-9284e980-96f4-11e7-813a-5e2b267fa75b.png)

## Checkresults

![icinga2_elasticwriter_kibana_checkresult_01](https://user-images.githubusercontent.com/382049/30272394-9d2925fe-96f4-11e7-98d8-a122d88103da.png)
![icinga2_elasticwriter_kibana_checkresult_02](https://user-images.githubusercontent.com/382049/30272395-9d2ad214-96f4-11e7-8ca3-ab76e9a74916.png)


## Notifications

![icinga2_elasticwriter_kibana_notification](https://user-images.githubusercontent.com/382049/30272401-a32e7274-96f4-11e7-8927-5dca5878c3f2.png)


## Statechange

![icinga2_elasticwriter_kibana_statechange](https://user-images.githubusercontent.com/382049/30272404-a91a640e-96f4-11e7-8499-7151f2e8ecb7.png)

**Comment by dnsmichi** [comment]
Performance data can be enabled similar to GelfWriter with enable_send_perfdata to avoid huge documents by default.

**Comment by dnsmichi** [comment]
## enable_send_perfdata

`false` is the default.

![icinga2_elasticwriter_kibana_checkresult_send_enable_perfdata_false](https://user-images.githubusercontent.com/382049/30273884-300f19a4-96fb-11e7-89db-ec4c40a6b9c6.png)

**Comment by dnsmichi** [comment]
# HTTP Proxy Support

Nginx, etc.

-> Vagrant-Box: Icinga/icinga-vagrant#97

## Basic auth

`username` and `password` setting.

### Error handling

```
[2017-09-11 16:53:06 +0200] critical/ElasticWriter: 401 Unauthorized. The HTTP API requires authentication but no username/password has been configured.
```

```
[2017-09-11 16:55:50 +0200] critical/ElasticWriter: 401 Unauthorized. Please ensure that the user 'root' is able to authenticate against the HTTP API/Proxy.
```

## TLS 

`enable_ssl` and the same options as the InfluxdbWriter. Check the docs for details.

![screen shot 2017-09-11 at 17 26 09](https://user-images.githubusercontent.com/382049/30283235-ce970d4a-9717-11e7-8523-69c97c8ee4d4.png)

**Comment by dnsmichi** [comment]
Basic auth/TLS only is supported with an HTTP proxy in front of Elasticsearch. Will be added separately in #5569.

**Comment by dnsmichi** [comment]
Note: This feature will be renamed for 2.8 to better reflect its purpose. `ElasticsearchWriter` specifies the backend, no need for a full Elastic stack here.
