### ISSUE TITLE
Review documentation for enhanced CSR signing and update migration chapter for 2.8

### ISSUE THREAD

**Issue by dnsmichi** [Icinga/icinga2#5680]
# Tasks

* [x] Client setup
* [x] Windows wizard including screenshots
* [x] Migration chapter with detailed examples on how to proceed
* [x] Link from Troubleshooting chapter into Migration chapter
