### ISSUE TITLE
Update Windows wizard from enhanced CSR signing (optional ticket)

### ISSUE THREAD

**Issue by dnsmichi** [Icinga/icinga2#5681]
Blocked by #5545 

# Tasks

* [x] Terminology on "Master" nodes - "master/satellite"
* [x] Optional ticket - verify node setup CLI command
* [x] Asynchronous CSR signing with no immediate answer
* [x] Dokumentation, Screenshots

**Comment by dnsmichi** [comment]
Wizard is currently here:

```
Running command 'icinga2.exe node setup --master_host mbmif.int.netways.de,5665 --endpoint mbmif.int.netways.de,mbmif.int.netways.de,5665 --accept-config --accept-commands --trustedcert "C:\Users\michi\AppData\Local\Temp\tmp1D62.tmp" --cn "DESKTOP-IHRPO96" --zone "DESKTOP-IHRPO96"' produced the following output:

critical
```

Needs a proper error handling for pending "no ticket" answers.

**Comment by dnsmichi** [comment]
```
[2017-11-02 16:17:27 +0100] information/ApiListener: New client connection for identity 'winmif' from [::ffff:10.0.10.57]:51429 (certificate validation failed: code 18: self signed certificate)
[2017-11-02 16:17:27 +0100] notice/ApiListener: New JSON-RPC client
[2017-11-02 16:17:27 +0100] notice/WorkQueue: Spawning WorkQueue threads for 'JsonRpcConnection, #1'
[2017-11-02 16:17:27 +0100] notice/JsonRpcConnection: Received 'icinga::Hello' message from 'winmif'
[2017-11-02 16:17:27 +0100] notice/JsonRpcConnection: Received 'pki::RequestCertificate' message from 'winmif'
[2017-11-02 16:17:27 +0100] information/JsonRpcConnection: Received certificate request for CN 'winmif' not signed by our CA.
[2017-11-02 16:17:27 +0100] information/JsonRpcConnection: Certificate request for CN 'winmif' is pending. Waiting for approval.
```

I still need to add something to the client that the request is pending, e.g. after installing the service.

**Comment by dnsmichi** [comment]
![screen shot 2017-11-02 at 16 24 39](https://user-images.githubusercontent.com/382049/32334283-5dd12fe0-bfea-11e7-91bf-86014f2e7847.png)

**Comment by dnsmichi** [comment]
While at it, the inputs via form do not trim strings as we do with the node wizard. I'm fixing this as part of this update.

![screen shot 2017-11-03 at 13 44 03](https://user-images.githubusercontent.com/382049/32374267-301cf4a4-c09d-11e7-9896-3f62cfd34b83.png)
