### ISSUE TITLE
Evaluate Prometheus integration (enablement for container & Kubernetes monitoring)

### ISSUE THREAD

**Issue by dnsmichi** [Icinga/icinga2#6419]
# Story

Icinga follows the host/service object approach. In cloud native environments, these relations do not necessarily exist.

A Kubernetes container cluster environment consists of containers and pods, running the production web server environment for example. Whenever 2 out of 10 containers fail, the website is still operational. This implies that we'd use sort of a business process logic.

Additionally, a one-time check may fail, but 5 seconds later the container cluster healed itself already. This could generate a false positive alarm, and the traditional state a plugin poll model fails in this regard.

This gets even worse with check states in a defined interval letting the service flap between states, and you are not able to detect failures.

Last but not least, Icinga needs access to all of these details. So actually we would need to create 

- inventory dummy service checks or a dedicated module storing and caching data
- Business process like logic applied onto that data
- Scale this in a way that it works with 100k+ containers
- Visualize this in a proper way in Icinga Web
- Support for multi cloud environments

## Conclusion

Instead, a new approach is needed with fetching metrics from $container orchestrator APIs, and calculate trends and alerts over time. With leveraging the logic of fetching that data, and aggregating them into APIs and dashboards, we should be able to combine both worlds, ranging from the traditional blackbox monitoring to detailed whitebox monitoring.

Therefore I am suggesting to look into integrations with Prometheus in this issue.

# Ideas

![IMG_5158](https://user-images.githubusercontent.com/382049/71096942-7ee2af00-21af-11ea-8534-99ea5e30cf7a.jpg)

## Prometheus

The basic principle is to provide HTTP endpoints exposing different metric groups

- Work (application)
- System (host, node)
- Events (anything else)

Prometheus can be configured to regularly scrape these HTTP endpoints and collect the metrics. It provides its own TSBD backend, and exposes access to the data via the REST API.

https://prometheus.io/docs/introduction/overview/
https://prometheus.io/docs/prometheus/latest/querying/api/

### Metric Format

https://prometheus.io/docs/instrumenting/exposition_formats/

Example:
```
# HELP node_context_switches Total number of context switches.
# TYPE node_context_switches counter
node_context_switches 1.33950265e+08
# HELP node_cpu Seconds the cpus spent in each mode.
# TYPE node_cpu counter
node_cpu{cpu="cpu0",mode="guest"} 0
node_cpu{cpu="cpu0",mode="guest_nice"} 0
node_cpu{cpu="cpu0",mode="idle"} 847133.19
node_cpu{cpu="cpu0",mode="iowait"} 395.78
node_cpu{cpu="cpu0",mode="irq"} 0
node_cpu{cpu="cpu0",mode="nice"} 67.55
node_cpu{cpu="cpu0",mode="softirq"} 46.87
node_cpu{cpu="cpu0",mode="steal"} 0
node_cpu{cpu="cpu0",mode="system"} 2302.62
node_cpu{cpu="cpu0",mode="user"} 4965.76
# HELP node_disk_bytes_read The total number of bytes read successfully.
# TYPE node_disk_bytes_read counter
node_disk_bytes_read{device="sda"} 1.756875776e+09
node_disk_bytes_read{device="sda1"} 1.75574016e+09
# HELP node_disk_bytes_written The total number of bytes written successfully.
# TYPE node_disk_bytes_written counter
node_disk_bytes_written{device="sda"} 3.7833327616e+10
node_disk_bytes_written{device="sda1"} 3.7833327616e+10
```

### Frontend

A management and inspection interface is available.

![Screen Shot 2019-12-18 at 16 02 55](https://user-images.githubusercontent.com/382049/71097180-e3057300-21af-11ea-9404-e62b26a10944.png)

Prometheus is a first class citizen in Grafana as datasource, fully supporting the query language. The setup is straight forward.
https://prometheus.io/docs/visualization/grafana/

![Screen Shot 2019-12-18 at 16 05 30](https://user-images.githubusercontent.com/382049/71097423-3c6da200-21b0-11ea-9573-4243f1a1fb11.png)

### Node Exporters

https://prometheus.io/docs/instrumenting/exporters/

#### Application /metrics 

An example already exists in IcingaDB, we've found this very easy to implement to immediately measure the application performance.

https://github.com/Icinga/icingadb/blob/master/prometheus/prometheus.go

### Push Gateway

https://prometheus.io/docs/instrumenting/pushing/
https://github.com/prometheus/pushgateway/blob/master/README.md

Example:

```
  cat <<EOF | curl --data-binary @- http://pushgateway.example.org:9091/metrics/job/some_job/instance/some_instance
  # TYPE some_metric counter
  some_metric{label="val1"} 42
  # TYPE another_metric gauge
  # HELP another_metric Just an example.
  another_metric 2398.283
  EOF
```

Golang client: https://github.com/prometheus/client_golang/blob/master/prometheus/push/push.go

### Client libraries

https://prometheus.io/docs/instrumenting/clientlibs/

### Kubernetes

https://github.com/kubernetes/kube-state-metrics

# Discussion

https://community.icinga.com/t/icinga-and-prometheus-whats-the-difference/177/2
https://twitter.com/dnsmichi/status/1207060828702334978

https://github.com/Icinga/icinga2/issues/6073#issuecomment-509096180
https://github.com/Icinga/icinga2/issues/6072

# Tasks

- [ ] /metrics scrape endpoint
- [ ] Push and Replay gateway
- [ ] Query Prometheus, receive alerts

Optional:

Consider creating node exporters which for both, Icinga and Prometheus to scrape metrics. E.g. with Icinga parsing a Prometheus Node Exporter endpoint and then "doing something". Maybe we can be creative and use this detail in the event framework.

## /metrics scrape target

- [ ] Grouping of metrics
- [ ] Metadata from objects, like custom variables?
- [ ] Add filter targets, which syntax?

### Configuration

- [ ] Enable it by default?
- [ ] Different port, making this special to the environment?
- [ ] Which metrics?
  - [ ] /v1/status (self health check)
  - [ ] host/service performance data
- [ ] Specific templates and values exposed being hardcoded, or configurable similar to the InfluxDB feature?

## Push/Replay Gateway

The push gateway can be used to send live metrics into Prometheus, similar to passive check results known from Icinga. 

**Important**: This gateway does not allow to specify a timestamp. In this regard, the Icinga cluster replay log will not work with historical data, any older check results and metrics would still be passed as "current".

An alternative idea would be to use the replay feature, file based: https://github.com/prometheus/prometheus/pull/5887

Consider this during evaluation/implementation, also with performance and IO in mind. 

Also, https://github.com/jupp0r/prometheus-cpp uses the curl interface to interact with the REST API. We should use our Boost ASIO/Beast stack similar to the other features.

Serialize data: https://github.com/jupp0r/prometheus-cpp/blob/master/core/src/text_serializer.cc 

- [ ] PoC implementation as Icinga feature
- [ ] Replay tool tests and additional PoC
- [ ] Performance tests
- [ ] Redis cache, API event streams alternative?

## Query Prometheus, Receive Alerts

- [ ] Grafana datasource
- [ ] Alerts from Prometheus to Icinga with using the REST API
- [ ] Direct access via feature read and write?
- [ ] Check plugin

### Grafana datasource

Either the REST API, or go with IcingaDB. The latter provides access to historical data which can be incorporated into correlations with other datasources.

Create and maintain an official plugin for Grafana.

### Alerts

Similar to Slack notifications, and known from Logstash, we could contribute an alert integration for Icinga, written in Golang. 

https://prometheus.io/docs/alerting/configuration/

For future strategic decisions, keep this in mind whenever our Events, Incidents, Notifications framework comes to life.

### Direct access

This needs some groundbreaking changes with allowing to execute checks in memory in Icinga, and query external data sources. We thought about this for MySQL already, but doing that inside the DSL and C++ may create yet another monolith hard to maintain and debug.

Better look for external modules/daemons which can execute checks, and feed that back to the core.

### Check Plugin

https://github.com/prometheus/nagios_plugins
https://github.com/claranet/nagitheus

> TBD, I am not sure if that's the right track to go.

**Comment by dnsmichi** [comment]
https://github.com/jupp0r/prometheus-cpp

**Comment by dnsmichi** [comment]
Different approach idea with a metrics writer:

# Icinga to Prometheus

- Push gateway doesn't allow to specify the timestamp. No Icinga cluster replay of metric data possible. https://prometheus.io/docs/practices/pushing/

## Push Gateway

https://prometheus.io/docs/instrumenting/pushing/
https://prometheus.io/docs/instrumenting/clientlibs/

## Implementation

- HTTP Requests
- Serialize Metrics https://github.com/jupp0r/prometheus-cpp/blob/master/core/src/text_serializer.cc
- Escape certain strings

Needs a work queue or buffer being flushed, similar to InfluxDB.

**Comment by dnsmichi** [comment]
For the /metrics endpoint, we could also provide something like the SSL exporter with the /probe endpoint. Or we somehow allow to put Icinga filters towards the API. It may also be the case that a proxy daemon up front, which handles the long requests.

More updates soon, until I get things sorted out with testing and analysing.

**Comment by dnsmichi** [comment]
I've updated the original post with a design draft/concept.

**Comment by dnsmichi** [comment]
Assigning to the next feature milestone, I'd like to keep working on this in 2020 til IcingaConf.

**Comment by roidelapluie** [comment]
The icinga satellites might use thanos (https://thanos.io) to send their data to a central location. Thanos is a sidecar for Prometheus.

**Comment by martialblog** [comment]
Just FYI, we recently released a check plugin that can be used to evaluate PromQL/Alerts via Icinga et al. https://github.com/NETWAYS/check_prometheus

**Comment by martialblog** [comment]
Regarding the `/metrics` endpoint in Icinga2, while a native endpoint in the application would be interesting, it is something a "sidecar" exporter can also provide. Other tools have a similar approach (e.g. nginx-prometheus-exporter, apache-exporter, mysql-exporter)

Examples for Icinga2:

- https://github.com/martialblog/icinga2-exporter
- https://github.com/opsdis/icinga2-exporter

**Comment by martialblog** [comment]
There is a dedicated issue now for introducing a Prometheus Writer: https://github.com/Icinga/icinga2/issues/9900

**Comment by martialblog** [comment]
Also https://github.com/Icinga/icinga-kubernetes
