### ISSUE TITLE
Revise stream exception handling

### ISSUE THREAD

**Issue by dnsmichi** [Icinga/icinga2#7159]
- [ ] fstreams from the Utility class
- [ ] boost filesystem exceptions
- [ ] Classes and functions using these methods and not catching them (e.g. CLI commands when temp file creation fails)

**Comment by htriem** [comment]
@Al2Klimov

**Comment by Al2Klimov** [comment]
# Task

Explain the instructions you received on this as detailed as possible (but <=1 DIN A4 page 😉).

**Comment by htriem** [comment]
I checked all my notes from all time, even correspondence with Michi - I don't think I was ever briefed on this in a major way.
