### ISSUE TITLE
Review notification engine

### ISSUE THREAD

**Issue by dnsmichi** [Icinga/icinga2#7161]
Will be updated, @lippserd 

## Engine 

- [ ] Reminder notifications should use a "scheduler" similar to checks, instead of the current timer #4594 
- [ ] Avoid code duplication from filter checks:
  - event triggered from process check result
  - reminder notifications
- [ ] Keep track of filtered notifications and schedule them at a later point: #4503
  - [ ] Start notifications after a downtime ends #5919 
- [ ] Evaluate a better design for "one time notifications", instead of interval=0 #7099 
- [ ] Notification results #6722 

### Cluster

- [ ] Delayed notifications (times.begin/end) in HA enabled zones #4995 
- [ ] Timezone support for TimePeriod objects #5374 

## Others

- [ ] Problem IDs for notifications #5158 
- [ ] Output based notifications (stalking) #5321

**Comment by Crunsher** [comment]
Also relevant: #7086 
Being able to reschedule Notifcations to after the Startup is done will fix this.

**Comment by dgoetz** [comment]
Is https://github.com/Icinga/icinga2/issues/6787 the same as https://github.com/Icinga/icinga2/issues/5919 or should it be added to the list?

**Comment by dnsmichi** [comment]
Technically the same issue/solution required.

**Comment by dnsmichi** [comment]
Assigning to 2.11 as ongoing tasks. Cannot guarantee that all issues will be solved with that release.

**Comment by Crunsher** [comment]
Current state and TODOS:
* Using a scheduler for problem notifications is great. 
* Unit tests for a component are hard

More on the issue of HA notifications:
When losing a node in HA, it takes a while for the remaining Node to update `paused` on the Notifications. Paused notifications are not sent because we assume someone else will take care of it. That way it's quite easy to lose Notifications. For problem notifications that is not too bad as you'll just miss one renotification and receive the next in the worst case.
For all other (Recovery, DowntimeStart... etc) this is a known Problem.
The only 100% way I can come up with to guarantee each and every notification is sent is for the notification components to start communicating.

**Comment by dnsmichi** [comment]
Assigned the selected issues to 2.11, the rest is up for 2.12.

**Comment by widhalmt** [comment]
ref/NC/627311

**Comment by widhalmt** [comment]
Could you add #6167 to list of issues to tackle during a rework? We have a setup where an object gets not-Ok outside of notification periods and no notification is sent when the notification period is reached. This should not be the case because problems could get away unnoticed.

**Comment by dnsmichi** [comment]
This issue is on hold for now, and needs a reorganisation with also planning the steps and time again. The previous attempt in solving this was not satisfying.
