### ISSUE TITLE
Add support for passing username and password to InfluxDB using basic auth

### ISSUE THREAD

**Issue by akrus** [Icinga/icinga2#7644]
## Is your feature request related to a problem? Please describe.

We're trying out https://github.com/VictoriaMetrics/VictoriaMetrics as a replacement for InfluxDB. The problem that it supports only basic auth and doesn't work when user/pass pair is passed as arguments.

## Describe the solution you'd like

An option allowing to change behavior would be nice.

## Describe alternatives you've considered

N/A

## Additional context

ref https://github.com/VictoriaMetrics/VictoriaMetrics/issues/240

**Comment by dnsmichi** [comment]
`username` and `password` already exists, https://icinga.com/docs/icinga2/latest/doc/09-object-types/#influxdbwriter

**Comment by dnsmichi** [comment]
I see. Since I have never heard of the mentioned product, nor we support it, I'd wait for them to implement full InfluxDB compatibility. I'm not a friend of making our feature more complicated than InfluxDB needs it.

**Comment by Al2Klimov** [comment]
@N-o-X Shall we implement this or wait for VictoriaMetrics/VictoriaMetrics/issues/240 ?

**Comment by foxos42** [comment]
We like to use an InfluxDB behind proxys with auth offloading so we need this feature to.

**Comment by aurrelhebert** [comment]
+1 as @foxos42 we are using Influx behind a basic auth (https://docs.influxdata.com/influxdb/v1.7/administration/authentication_and_authorization/#authenticate-requests) and can authenticate our requests in Icinga2

**Comment by Al2Klimov** [comment]
FYI I'd not like the basic auth and the regular one to exclude each other like https://github.com/ziirish/icinga2/commit/00d2aeda163312358f7526fa6be80075d639762b .

**Comment by N-o-X** [comment]
This is definitely something that should be easy to implement and, as we can already see in the issue history, very useful for some users. Thumbs up for implementing this 👍

**Comment by Al2Klimov** [comment]
## Tasks

* [ ] Create a Docker compose setup: Icinga 2 – Nginx reverse proxy – Influxdb – Grafana
* [ ] Make sure Icinga 2 can write some data through Nginx into Influxdb and they show up in Grafana
* [ ] Turn on Nginx basic auth
* [ ] Make sure Icinga 2 can't write anything anymore

**Comment by Yonas-net** [comment]
I have built a test setup like it is in the ``TODO: list`` above and came to the conclusion that if you enable the basic authentication of nginx, icinga2 is no longer authorized to write to Influxdb. It is also not possible to execute queries from grafana as long as the basic authentication of grafana is not activated. In the following you will find all steps i made for the test.

First I configured services for icinga2, influxdb and grafana in the ``docker-compose.yml.``
```
version: "3.8"

services:
  nginx-service:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - "./nginx:/etc/nginx/conf.d"
  influxdb-service:
    image: influxdb
    ports:
      - "8086:8086"
    volumes:
      - "./influxdb:/var/lib/influxdb"
    environment:
      INFLUXDB_DB: "icinga2"
      INFLUXDB_USER: "icinga2"
      INFLUXDB_USER_PASSWORD: "icinga2"
  grafana-service:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
    - "./grafana:/var/lib/grafana"
  icinga2:
    image: icinga/icinga2:latest
    volumes:
    - "./icinga2Volume:/data"
```

And after creating a new user for authentication, I added the following config to the ``nginx .conf``.
```
location / {
        auth_basic "Admin";
        auth_basic_user_file /etc/nginx/conf.d/.htpasswd;
        proxy_pass http://influxdb-service:8086;
    }
```
what this also includes that grafana can access the ``Influxdb`` via ``nginx`` with.

And then you have to enable the ``inluxdb feature`` in icinga2 and change the configuration of inluxdb object so that ``icinga2`` can also access the ``inluxdb`` via ``nginx``.

```
object InfluxdbWriter "influxdb" {
  host = "nginx-service"
  port = 80
  database = "icinga2"
  flush_threshold = 1024
  flush_interval = 10s
  host_template = {
    measurement = "$host.check_command$"
    tags = {
      hostname = "$host.name$"
    }
  }
  service_template = {
    measurement = "$service.check_command$"
    tags = {
      hostname = "$host.name$"
      service = "$service.name$"
    }
  }
}
```

And that's it, before i enabled the basic authentication, icinga2 was able to write to influxdb but after that i only get the following error message.

**Comment by Al2Klimov** [comment]
Extend InfluxdbWriter, so that it also accepts also the following config option:

```
  basic_auth = {
    username = "icinga"
    password = "icinga"
  }
```
