### ISSUE TITLE
Forbid modifications to `globals` namespace after evaluting top-level configuration

### ISSUE THREAD

**Issue by julianbrost** [Icinga/icinga2#9628]
### Suggestion

The suggestion is to deprecate all modifications to the `globals` namespace after the top-level of the configuration was evaluated. That is deprecate everything that would be prevented by https://github.com/Icinga/icinga2/pull/9607/commits/f75b77a33402090fcb41e0eeb710595c310a9684.

Example:

```
globals.foo = 23 // allowed

object HostGroup "g" {
	globals.bar = 42 // currently allowed, suggested to be deprecated
}
```

### Rationale

The phase of config loading where `object` and `apply` blocks are evaluated is done in parallel. So allowing modifications at that stage requires synchronization to ensure the consistency of the data structures. If we could freeze the globals namespace, this would allow to perform no locking at all. The globals namespace is accessed heavily during apply rule evaluation, one of the most expensive phases of config loading.

We couldn't do #9607 in 2.14 because it would have introduced a breaking change to how the configuration works in a way that Director would be affected. There is #9627 which does something similar in a compatible way. But this still performs some locking operations that would become unnecessary with a frozen globals namespace and no locking is cheaper than some locking for sure.

In general, the DSL doesn't provide synchronization mechanisms so if the configuration does something like this, it's likely to have race conditions. For example, Director stores a flag in globals to log a message only once, but due to the missing synchronization, this could also be logged multiple times. Of course, in this case it's not a critical failure, but it shows the potential for accidentally introducing bugs in the configuration. So the deprecation warning could even uncover bugs in user configuration.

### Tasks

- Wait for #9627 to be done (not strictly necessary, but I want to get that PR rather than add another dimension of complexity now).
- [x] Cherry-pick https://github.com/Icinga/icinga2/pull/9607/commits/f75b77a33402090fcb41e0eeb710595c310a9684 on top and benchmark it to assess the benefits this would have in the long term.
- [x] Coordinate with Director (if we deprecate it, there should also be a Director release that no longer needs this).
- [ ] ~Create a PR that adds a deprecation warning.~
- [ ] ~Create an issue for replacing the deprecation warning with the freeze in a later version.~
- [x] Skip deprecation because of https://github.com/Icinga/icingaweb2-module-director/issues/2700#issuecomment-1419460750 and https://github.com/Icinga/icinga2/issues/9628#issuecomment-1420552120

**Comment by Al2Klimov** [comment]
OK. I started this on #9627:

`for i in {1..10}; do time icinga2 daemon -C -x critical; done`

**Comment by Al2Klimov** [comment]
| real | user | sys |
|------|------|-----|
| 23m41,989s | 1056m24,028s | 207m46,986s |
| 24m10,306s | 1084m32,750s | 199m45,335s |
| 24m58,666s | 1152m39,816s | 168m35,401s |
| 25m16,643s | 1156m18,189s | 201m20,795s |
| 23m5,677s | 1044m19,698s | 186m54,275s |
| 24m26,794s | 1112m13,336s | 184m30,857s |
| 23m5,215s | 1049m22,950s | 186m35,814s |
| 23m30,688s | 1061m56,622s | 184m29,615s |
| 23m37,115s | 1073m8,501s | 185m36,210s |
| 22m32,282s | 1037m58,185s | 166m31,956s |

And now the same for https://github.com/Icinga/icinga2/pull/9627 + https://github.com/Icinga/icinga2/commit/f75b77a33402090fcb41e0eeb710595c310a9684 ...

**Comment by Al2Klimov** [comment]
| real | user | sys |
|------|------|-----|
| 23m29,593s | 1066m58,491s | 179m12,759s |
| 20m32,824s | 902m51,334s | 190m4,827s |
| 22m30,850s | 987m12,758s | 207m19,554s |
| 22m37,497s | 986m55,434s | 213m21,512s |
| 22m32,529s | 1013m7,710s | 184m28,031s |
| 22m29,642s | 1002m44,165s | 186m24,761s |
| 22m8,167s | 991m28,751s | 180m5,000s |
| 23m27,167s | 1028m19,987s | 217m15,860s |
| 20m26,033s | 910m15,849s | 177m42,772s |
| 22m3,554s | 978m20,090s | 195m19,011s |

> Shall I continue?

**Comment by julianbrost** [comment]
Looks like it indeed gives a few percent of improvement. So yes, please continue.

**Comment by Al2Klimov** [comment]
Please read the issue linked above this text and then -for the reasons I described there- just PRify f75b77a33402090fcb41e0eeb710595c310a9684 as you're the committer. I'll test it with Director.

**Comment by julianbrost** [comment]
So you're saying you have checked all uses of the `globals` namespace and all that would conflict the proposal in this issue are unreachable on current versions of Icinga 2 and therefore we should just skip the deprecation phase?

**Comment by Al2Klimov** [comment]
Yes, as I explained in the Director issue.

**Comment by Al2Klimov** [comment]
## #9627 + f75b77a33402090fcb41e0eeb710595c310a9684, Director flapping thresholds crashtest

![Bildschirm­foto 2023-02-07 um 11 26 03](https://user-images.githubusercontent.com/6053266/217221137-a01b5888-c970-4f1f-8520-0f1d74193875.png)
![Bildschirm­foto 2023-02-07 um 11 26 24](https://user-images.githubusercontent.com/6053266/217221133-20e1a3af-60e9-4ded-88ef-54982f70220a.png)

Purrs.
